### ISSUE TITLE
Implementation of Event Dispatcher

### ISSUE THREAD

**Issue by Rvanlaak** [asposeforcloud/Aspose_Cloud_SDK_For_PHP#21]
There are happening a lot of events in the SDK, which probably are interesting enought to get information about. By implementing a event dispatcher, and triggering events through the most important classes of the SDK, it will be possible for example to:

1. Add the [Stopwatch component](http://symfony.com/doc/current/components/stopwatch.html) in the [AsposeCloudBundle](https://github.com/asposeforcloud/asposesymfony) to monitor how long the processing takes
2. Manually add extra curl headers to each command, by triggering a 'util.processCommand' event
3. Register a listener to the [`Your pricing plan allows only` exception](https://github.com/asposeforcloud/Aspose_Cloud_SDK_For_PHP/blob/master/src/Aspose/Cloud/Common/Utils.php#L119), so users can do something usefull with this
4. Register a listener to the `Utils::validateOutput` function to add some extra validation for their own calls

Implementing an EventDispatcher will not break any code because no calls from the api do rely on anything but the classes from the `/Common` folder yet. Shall I start with making a first implementation?

**Comment by Rvanlaak** [comment]
Please reopen this issue, still working on this.

Some extra reading material about globals ;-) http://stackoverflow.com/questions/5166087/php-global-in-functions/5166527#5166527

**Comment by asposeforcloud** [comment]
@Rvanlaak The issue has been reopened.

Our concerned developer is out of office for today. As soon as he gets back, he will review and take necessary actions on the PRs / issues opened up over the weekend. Thank you for the contribution.

**Comment by Rvanlaak** [comment]
See PR #23

**Comment by masood-anwer** [comment]
Merged PR #23

**Comment by masood-anwer** [comment]
Getting error below while calling getProperties() method of Document class for Words, please take a look.

Fatal error: Call to a member function dispatch() on null in [Line](https://github.com/asposeforcloud/Aspose_Cloud_SDK_For_PHP/blob/master/src/Aspose/Cloud/Common/Utils.php#L122)

**Comment by Rvanlaak** [comment]
This is fixed in PR #24
