### ISSUE TITLE
Implementation of PSR Logger

### ISSUE THREAD

**Issue by Rvanlaak** [asposeforcloud/Aspose_Cloud_SDK_For_PHP#24]
Currently there is no logger, so all that happens is that Exceptions are thrown and users can try to catch those.

The SDK should allow users to log all actions, and should be able to inject their own `Logger` that implements [the standardized PSR-3 `LoggerInterface`](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-3-logger-interface.md)

My proposition:
1. Implement https://github.com/php-fig/log for a standard logger
2. Add getter/setter for the `$logger` in the AsposeApp
3. Inject the `Monolog/Logger` from the Symfony framework in the [`CloudBundle`](https://github.com/asposeforcloud/asposesymfony)

**Comment by masood-anwer** [comment]
Thank you for your purposed solution to implement logger feature. It would be good addition to SDK. Please feel free to move forward.
