### ISSUE TITLE
Implement OptionResolver for API calls

### ISSUE THREAD

**Issue by Rvanlaak** [asposeforcloud/Aspose_Cloud_SDK_For_PHP#27]
Currently it really is unclear what options / parameters are required, and which are optional.

What about implementing the [OptionsResolver](http://symfony.com/doc/current/components/options_resolver.html) for that? That way new features that use the parameters can get implemented more easy.

Default options can be configured really easy. The resolver will throw an `UndefinedOptionsException` when a bug occurs, so this will make the API way more stable.

First place where you could implement this (and get rid of the boilerplate code) is 
[the `WordDocument::splitDocument` call](https://github.com/asposeforcloud/Aspose_Cloud_SDK_For_PHP/blob/master/src/Aspose/Cloud/Words/Document.php#L133)

**Comment by Rvanlaak** [comment]
An example of the `OptionsResolver` implementation would be:
```php
use Symfony\Component\OptionsResolver\OptionsResolver;

...

    /**
     * @param array $options that will get processed using a OptionsResolver
     * <ul>
     *  <li>'from' => page number,</li>
     *  <li>'to' => page number,</li>
     *  <li>'format' => Returns document in the specified format,</li>
     *  <li>'storageName' => Name of the storage,</li>
     *  <li>'folder' => Name of the folder,</li>
     * </ul>
     *
     * @return string|boolean
     * @throws Exception
     * @see OptionsResolver
     */
    public function splitDocument(array $options=array())
    {
        $strURI = Product::$baseProductUri . '/words/' . $this->getFileName() . '/split?';

        $resolver = new OptionsResolver();
        $resolver->setDefined(array('folder', 'storage', 'from', 'to', 'format', 'zipOutput'));
        $options = $resolver->resolve($options);

        $strURI .=  http_build_query($options);
        $signedURI = Utils::sign($strURI);

        $responseStream = Utils::processCommand($signedURI, 'POST', '', '');

...
```

So, when an extra option is added to the API, it only has to be added to `setDefined`. Mandatory parameters can be set via `setRequired`.

**Comment by Rvanlaak** [comment]
See https://github.com/Rvanlaak/Aspose_Cloud_SDK_For_PHP/compare/Rvanlaak-options-resolver?expand=1 for an example of the implementation.

**Comment by Rvanlaak** [comment]
Made PR #28

**Comment by masood-anwer** [comment]
Merged PR. Thanks for the new feature.

**Comment by Rvanlaak** [comment]
Thanks, don't forget to release a new version. Since this one has a BC break, tag it `1.2.0`
