### ISSUE TITLE
 The requested package aspose/cloud-sdk-php 1.0.0 could not be found.

### ISSUE THREAD

**Issue by vanney9** [asposeforcloud/Aspose_Cloud_SDK_For_PHP#31]
when I running composer update, it shows  error below:
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package aspose/cloud-sdk-php 1.0.0 could not be found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

can anyone helps me.

**Comment by masood-anwer** [comment]
I have updated & run composer file and its working for me. Please read README file for installation or add following line to your composer.json file.

{
    require: {
        "aspose/cloud-sdk-php": "~1.1"
    }
}

Install the new dependencies by running "composer update" from the directory where your composer.json file is located.

**Comment by vanney9** [comment]
thanks a lot. I have fixed this problem in this way

**Comment by masood-anwer** [comment]
Thanks for your feedback. Please feel free to ask if you have any questions/issues about SDK, we will be happy to help you.
