### ISSUE TITLE
get the pdf forms

### ISSUE THREAD

**Issue by manojdhiman** [asposeforcloud/Aspose_Cloud_SDK_For_PHP#32]
I just want to get the forms field for the pdf . How can i achive this with this api???

can you show me an exaple ??

i am trying like this 

<?
ini_set('display_errors', '1');
require 'Aspose/Cloud/Pdf/Document.php';

$document=new Document;

echo $document->GetFormFields();

?>

**Comment by Rvanlaak** [comment]
```php
$document = new Document($fileName);
var_dump($document->getFormFields());
```

**Comment by manojdhiman** [comment]
can you put an index.php with working example??

**Comment by masood-anwer** [comment]
Please go through this URL to get form fields. http://www.aspose.com/docs/display/pdfcloud/Get+all+Form+Fields+from+the+PDF+Document

OR

You can use this example to code to fetch form fields from pdf document.

use Aspose\Cloud\Common\AsposeApp;
use Aspose\Cloud\Common\Product;
use Aspose\Cloud\Pdf\Document;

AsposeApp::$appSID = "...";
AsposeApp::$appKey = "...";
Product::$baseProductUri = "http://api.aspose.com/v1.1";

$document = new Document("Document1.pdf");
$fields = $document->getFormFields();

echo "Count: " . count($fields) . "\n";
foreach($fields as $field) {
  echo "Name: {$field->Name}\n";
  echo "Type: {$field->Type}\n";
  echo "Values: " . count($field->Values) . "\n";
  echo "\n";
}
