### ISSUE TITLE
Bug in Pdf Converter->convertLocalFile when converting to docx

### ISSUE THREAD

**Issue by Rvanlaak** [asposeforcloud/Aspose_Cloud_SDK_For_PHP#35]
The `convertLocalFile` function does not allow me to convert PDF files to DOCX, while this is possible according to your website.

There isn't given an error, the file is just saved and saved to the drive. When we open the file it contains:

    <Error><Message>Format 'docx' is not supported.</Message></Error>

This should be properly handled by the SDK.

**Comment by masood-anwer** [comment]
This is not SDK issue, its an API issue. I have reported this issue to concern developer. Please report it on Aspose forums so you can get notification once issue is fixed. However, I have added check to generate error instead of writing file to disk.
