### ISSUE TITLE
Unable to instantiate a class

### ISSUE THREAD

**Issue by SivaRamRIT** [asposeforcloud/Aspose_Cloud_SDK_For_PHP#38]
I am trying to call a method from BarCodeReader.php in my index page. I get an error 'class not found'. I tried include, require but I am not able to make it work. Could you guys please post an example showing how to include the files correctly and call the class methods. Thanks.

**Comment by Rvanlaak** [comment]
Title, really?

**Comment by SivaRamRIT** [comment]
I apologize, I am a newbie in Github.

**Comment by Rvanlaak** [comment]
You should only require the `autoload.php` script that has been created in your vendor folder after `composer install`.

**Comment by masood-anwer** [comment]
Please visit this link for Barcode Reader usage examples. 
https://github.com/asposeforcloud/Aspose_Cloud_SDK_For_PHP/wiki/Working-with-Barcode-Recognition

**Comment by SivaRamRIT** [comment]
Thanks for the suggestions.
This is what I tried:
1)I added the  "require": {
        "aspose/cloud-sdk-php": "~1.1" to composer.json file
2) I tried 'composer install' and 'composer update'. Both returned the same error message as below

![capture](https://cloud.githubusercontent.com/assets/6789238/8624356/4933c5fa-2705-11e5-8301-c05469a5efa5.PNG)

**Comment by masood-anwer** [comment]
Thanks for sharing error message. I have just installed SDK via composer to make sure the error and installed it successfully. Can you please share your composer.json file or you can create new composer.json file, add following code in it and execute "composer update" command.
```json
{
    "require": {
        "aspose/cloud-sdk-php": "~1.1"
    }
}
```
Please feel free to contact if you still find the issue.

**Comment by SivaRamRIT** [comment]
It works now. The default composer.json comes with the below code
{
    "description": 	"This repository contains Aspose Cloud SDK for PHP source code. Aspose Cloud SDK for PHP lets PHP developers convert and process a variety of file formats in the cloud quickly and easily.",
    "name": 		"aspose/cloud-sdk-php",
    "type": 		"library",
    "keywords" : 	["aspose", "php", "aspose cloud"],
	"homepage": 	"https://github.com/asposeforcloud/Aspose_Cloud_SDK_For_PHP",
	"authors": [
        {
            "name": 	"Assad Mahmood Qazi",
            "email": 	"assadvirgo@gmail.com"
        }
    ],
    "require": {
        "php": ">=5.3.2",
        "ext-curl": "*",
        "symfony/event-dispatcher": "~2.0",
        "symfony/options-resolver": "~2.0",
        "psr/log": "~1.0"
    },
    "autoload": {
        "psr-0": {
            "Aspose": "src/"
        }
    }
}

If I add "aspose/cloud-sdk-php": "~1.1"   in the require section and run composer update or install  it returns the error. But if I clear everything else and add

{
    "require": {
        "aspose/cloud-sdk-php": "~1.1"
    }
}

this only as you said, it works fine. Thanks a lot.
